name: wheels

on: workflow_dispatch

env:
    # nmslib does not build on 32bit Windows
    # https://cibuildwheel.readthedocs.io/en/stable/options/
    # cp39-win_amd64
    # cp37-win32 cp38-win32 cp39-win32
    # TODO: manylinux aarch64
    # TODO: macos arm64
    CIBW_SKIP: cp2* pp* cp35* cp36* cp37* *-win32 *-musllinux* *-macosx_*_universal2* *win_arm64* *-manylinux_arm64 *-manylinux_i686 *-manylinux_ppc64le *-manylinux_s390x *-manylinux_aarch64
    CIBW_BEFORE_BUILD: pip3 install -r requirements.txt --upgrade
    CIBW_TEST_SKIP: "*-macosx_arm64"
    #CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
    CIBW_ARCHS: all

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-11, windows-2019, ubuntu-20.04]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4

      - name: Install cibuildwheel
        run: python3 -m pip install cibuildwheel==2.20.0

      - name: Build wheels
        run: python3 -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
