name: wheels

on: workflow_dispatch

env:
    # nmslib does not build on 32bit Windows
    # https://cibuildwheel.readthedocs.io/en/stable/options/
    # cp39-win_amd64
    CIBW_SKIP: cp2* pp* cp35* cp36* cp37-win32 cp38-win32 cp39-win32 cp310-win32 cp311-win32
    CIBW_BEFORE_BUILD: pip install -r requirements.txt --upgrade

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Build wheels
        uses: joerick/cibuildwheel@v1.10.0

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install optional dependencies
        continue-on-error: true
        run: |
          pip install mlpack --upgrade

      - name: Build sdist
        run: python setup.py sdist

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.tar.gz
